const games = [
    
    
        [1, "Anna Ternheim, David Ferguson - The Longer The Waiting (The Sweeter The Kiss)", "The Nightwatch"],
        [2, "Ashtar Command - Deadman's Gun", "Red Dead Redemption"],
        [3, "AWJC Media - Wii Koopa Cape", "Mario Kart"],
        [4, "Mice On Venus", "Minecraft"],
        [5, "Chris Remo - Ol' Shoshone", "Firewatch"],
        [6, "Coeur De Pirate - Pilgrims on a Long Journey", "Child of Light"],
        [7, "Dan Romer, Meredith Godreau - We Will Rise Again", "Far Cry 5"],
        [8, "D'Angelo - Unshaken", "Unshaken"],
        [9, "Daniel Lanois - That's The Way It Is", "Red Dead Redemption"],
        [10, "Ashley Barrett - Good Riddance (Eurydice Solo)", "Hades"],
        [11, "Florence + The Machine - I Will Be", "Final Fantasy XV"],
        [12, "Giles Lamb - Dead Island Trailer Theme (Original Soundtrack)", "Dead Island"],
        [13, "Good Knight Productions - DK Island Swing", "Donkey Kong Country"],
        [14, "Gustavo Santaolalla - The Last of Us", "The Last of Us"],
        [15, "Jeremy Soule - From Past to Present", "Elder Scrolls V"],
        [16, "Jerry Martin - Under Construction", "The Sims"],
        [17, "Jon Batiste - Green Hill Zone", "Elder Scolls V"],
        [18, "Kirby's Dream Band - King Dedede", "King Dedede"],
        [19, "Mike Oldfield - Nuclear", "Metal Gear Solid 5"],
        [20, "Ready Player Piano - Grass Land", "Super Mario Brothers 3"],
        [21, "Sean Dagher - Star of the County Down", "Assassin's Creed 4"],
        [22, "Starsailor - Way to Fall", "Metal Gear Solid 5"],
        [23, "Mario Title Theme", "Super Mario Brothers 64"],
        [24, "Vicarious Visions Audio - Crash Bandicoot Main Theme", "Crash Bandicoot"],
        [25, "Vicarious Visions Audio - Hog Wild", "Crash Bandicoot"],
        [26, "Bomberman Theme (Area 1)", "Bomberman"],
        [27, "Castlevania 2 Theme (Bloody Tears)", "Castlevania"],
        [28, "Castlevania Stage 1 Theme (Vampire Killer)", "Castlevania"],
        [29, "Contra Theme (Jungle Theme)", "Contra"],
        [30, "Crash Bandicoot Theme", "Crash Bandicoot"]
        [31, "Dire Dire Docks Theme", "Super Mario Brothers 64"],
        [32, "Donkey Kong Country Theme", "Donkey Kong Country"],
            [33, "Dr Wily's Castle Theme", "Mega Man 2"],
            [34, "DuckTales (The Moon Theme)", "Duck Tales"],
            [35, "Dumb Ways to Die Theme (Game Music)", "Dumb Ways to Die"],
            [36, "Final Fantasy VII Prelude", "Final Fantasy VII"],
            [37, "Flappy Bird (Sound Effects)", "Flappy Bird"],
            [38, "Ice Cap Zone Act 1 Theme", "Sonic the Hedgehog 3"],
            [39, "Kirby Gourmet Race Theme", "Kirby Super Star"],
            [40, "Kirby's Dream Land (Green Greens Theme)", "Kirby's Dream Land"],
            [41, "Metroid Theme", "Metroid"],
            [42, "Minecraft Theme (Calm 1)", "Minecraft"],
            [43, "Ocarina of Time (Opening Theme)", "Legend of Zelda Ocarina"],
            [44, "Pacman Theme", "Pacman"],
            [45, "Pokemon Red", "Pokemon"],
            [46, "Song of Storms", "Legend of Zelda Ocarina"],
            [47, "Super Mario World Theme (Overworld Theme)", "Overworld"],
            [48, "Tetris Theme", "Tetris"],
            [49, "The 7th Guest Theme", "7th Guest"],
            [50, "The Legend of Zelda Theme", "Legend of Zelda"],
            [51, "Tomb Raider Theme", "Tomb Raider"],
            [52, "Underwater Theme", "Super Mario Brothers 64"],
            [53, "Worms Theme", "Worms"],
            [54, "Zelda II_ The Adventure of Link (Palace Theme)", "Legend of Zelda"],
            [55, "Zelda's Lullaby", "Legend of Zelda"]
      
     
]