const musicals = [
    [1, "Beauty and the Beast", "Be Our Guest"],
    [2, "Cabaret", "Cabaret"],
    [3, "Cats", "Memory"],
    [4, "Cats", "Mr Mistoffelees"],
    [5, "Chicago", "All That Jazz"],
    [6, "Dear Evan Hansen", "You Will Be Found"],
    [7, "Gentlemen Prefer Blondes", "Diamonds Are a Girl's Best Friend"],
    [8, "Evita", "Don't Cry for Me Argentina"],
    [9, "Fiddler on the Roof", "If I Were a Rich Man"],
    [10, "Flower Drum Song", "I Enjoy Being a Girl"],
    [11, "Frozen", "Let It Go"],
    [12, "Grease", "Summer Nights"],
    [13, "Guys and Dolls", "Sit Down, You're Rockin' the Boat"],
    [14, "Hairspray", "You Can't Stop the Beat"],
    [15, "Hamilton", "Alexander Hamilton"],
    [16, "Hamilton", "My Shot"],
    [17, "Hamilton", "Who Lives, Who Dies, Who Tells Your Story"],
    [18, "Wicked", "Defying Gravity"],
    [19, "In the Heights", "Breathe"],
    [20, "Les Misérables", "I Dreamed a Dream"],
    [21, "Mamma Mia!", "Mamma Mia"],
    [22, "Mamma Mia!", "Super Trouper"],
    [23, "Miss Saigon", "Last Night of the World"],
    [24, "Spamalot!", "Always Look on the Bright Side of Life"],
    [25, "My Fair Lady", "With a Little Bit of Luck"],
    [26, "My Fair Lady", "I Could Have Danced All Night"],
    [27, "Show Boat", "Ol' Man River"],
    [28, "On the Town", "New York, New York"],
    [29, "Once", "Falling Slowly"],
    [30, "Porgy and Bess", "Summertime"],
    [31, "Rent", "Seasons of Love"],
    [32, "Singing in the Rain", "Singing in the Rain"],
    [33, "South Pacific", "I'm Gonna Wash That Man Right Outa My Hair"],
    [34, "Sweet Charity", "Hey Big Spender"],
    [35, "The Bodyguard", "I Will Always Love You"],
    [36, "The Book of Mormon", "Hello"],
    [37, "A Little Night Music", "Send in the Clowns"],
    [38, "The Commitments", "Mustang Sally"],
    [39, "Funny Girl", "Don't Rain on My Parade"],
    [40, "The Greatest Showman", "From Now On"],
    [41, "The Music Man", "Ya Got Trouble"],
    [42, "The Music Man", "76 Trombones"],
    [43, "Phantom of the Opera", "Music of the Night"],
    [44, "The Rocky Horror Picture Show", "Time Warp"],
    [45, "The Rocky Horror Picture Show", "Sweet Transvestite"],
    [46, "The Wizard of Oz", "If I Only Had a Brain"],
    [47, "Tina", "River Deep Mountain High"],
    [48, "Carousel", "You'll Never Walk Alone"],
    [49, "West Side Story", "Maria"],
    [50, "Wicked", "Popular"],
    [51, "Willy Wonka", "Oompa Loompa"],
    [52, "42nd Street", "42nd Street"],
    [53, "A Chorus Line", "One"],
    [54, "A Chorus Line", "What I Did For Love"],
    [55, "Annie", "Tomorrow"],
    [56, "Annie Get Your Gun", "There's No Business Like Show Business"],
    [57, "Annie", "It's a Hard Knock Life"],
    [58, "Anything Goes", "Anything Goes"],
    [59, "Young Frankenstein", "Putting on the Ritz"],
    [60, "The Meaning of Life", "Every Sperm is Sacred"]
];